#debug = true

# Bus type values are available here (impl BusType > "Source"):
# https://docs.rs/evdev/latest/evdev/struct.BusType.html

[internal.legion_controller]
bus_type = 0x3
vendor = 0x17ef
product = 0x6184

[internal.isa]
bus_type = 0x10

[internal.i8042]
bus_type = 0x11

[internal.i2c]
bus_type = 0x18

[case.tango_tactical]
bus_type = 0x5
vendor = 0x04e8
product = 0x7021